// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9oqas0HMoYsETlCVud36J1WGMhYA_Zwc',
    appId: '1:713394797306:web:cca47c0f8af51aeb542743',
    messagingSenderId: '713394797306',
    projectId: 'social-app-9b53c',
    authDomain: 'social-app-9b53c.firebaseapp.com',
    storageBucket: 'social-app-9b53c.appspot.com',
    measurementId: 'G-LJ2C7VG2YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-TdZk9cMkmRln-UaFzzuvMGovZMud6Nk',
    appId: '1:713394797306:android:fc91355ba19f2d8d542743',
    messagingSenderId: '713394797306',
    projectId: 'social-app-9b53c',
    storageBucket: 'social-app-9b53c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACq1qHrIFQ12xop9pYCJxDFoTGcwHtZE4',
    appId: '1:713394797306:ios:ff29b2cb8b3b2f51542743',
    messagingSenderId: '713394797306',
    projectId: 'social-app-9b53c',
    storageBucket: 'social-app-9b53c.appspot.com',
    iosClientId: '713394797306-jnlc9q52mvd7i5faeforqtq7v9q4e4r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACq1qHrIFQ12xop9pYCJxDFoTGcwHtZE4',
    appId: '1:713394797306:ios:ff29b2cb8b3b2f51542743',
    messagingSenderId: '713394797306',
    projectId: 'social-app-9b53c',
    storageBucket: 'social-app-9b53c.appspot.com',
    iosClientId: '713394797306-jnlc9q52mvd7i5faeforqtq7v9q4e4r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
